# FROM node:18-alpine
FROM node@sha256:4bdb3f3105718f0742bc8d64bb4e36e8f955ebbee295325e40ae80bc8ef78833

RUN apk --no-cache update && \
    apk --no-cache upgrade && \
    apk --no-cache add git

RUN git config --global --add safe.directory .

# Install app dependencies
COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN git submodule update --init --recursive
RUN yarn build

EXPOSE 8000
CMD [ "node", "build/src/index.js" ]