import { Generated } from 'kysely';

// IDs are numbers from postgres uuid generator (under the Kysely hood)
export type ID = Generated<string>;

export interface Identifiable {
  id: Generated<ID>;
}

// These get autogenerated on row creation
// Should add a trigger which bumps last updated on update
export interface Timestamps {
  created: Date;
  last_updated: Date;
}

export interface DbObject extends Identifiable, Timestamps {}
